# Generated by Django 3.2.5 on 2021-07-17 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('short_name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.CharField(default='', editable=False, max_length=50)),
                ('date', models.DateField(default=datetime.date(2021, 7, 17))),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_code', models.CharField(max_length=20)),
                ('element_value', models.CharField(max_length=100)),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catalogmodel')),
            ],
        ),
    ]
