# Generated by Django 3.2.5 on 2021-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='version',
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
    ]
