# Generated by Django 3.2.5 on 2021-07-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_catalogmodel_version'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogModel',
            new_name='Catalog',
        ),
    ]
